# FROM node:lts-alpine
FROM node:16-alpine

WORKDIR /app
COPY package.json ./

RUN npm install

# build時間が短くなる

COPY . .

# デバッグ用にnode_modulesの内容を確認
# RUN ls -la /app

CMD ["npm", "start"]
# CMD ["npm", "run", "build"]

# CMD npm start --host 0.0.0.0 --port 80 --disableHostCheck true

# RUN npm run build

# FROM nginx:alpine
# COPY --from=builder /app/build /usr/share/nginx/html